
keyboard_cmd = {
    'search': {'in': ['search', 'поиск', 'искать', 'найти'],
              'out': ['Я нашел'],
              'key': 'search',
              'keyboard': 'search'},
    'next': {'in': ['next', 'следующий'],
              'out': ['Следующий'],
              'key': 'next',
              'keyboard': 'search'},
    'previous': {'in': ['previous', 'предыдущий'],
             'out': ['Предыдущий'],
             'key': 'previous',
             'keyboard': 'search'},
    'hello': { 'in': ['hello', 'привет', 'hello', 'hi', 'privet', 'hey'],
              'out': ['Приветствую!', 'Здравствуйте!', 'Привет!'],
              'key': 'helloo',
              'keyboard': 'menu' },
    'menu': { 'in': ['back', 'назад', 'меню'],
             'out': ['Назад' ],
              'key': 'back',
              'keyboard': 'back'},
    'back': {'in': ['назад'],
             'out': ['Назад'],
             'key': 'back',
             'keyboard': 'menu'},
    'black_list': {'in': ['black_list', 'черный список'],
             'out': ['Черный список'],
             'key': 'black_list',
             'keyboard': 'menu'},
    'favorites': {'in': ['favorites', 'избранное'],
             'out': ['Избранное'],
             'key': 'favorites',
             'keyboard': 'menu'},
    'none': {'in': [],
             'out': ['Команды которые знает бот:\n привет\n поиск\n следующий\n предыдущий\n избранное\n черный список'],
             'key': 'none',
             'keyboard': 'menu'}
}
settings = keyboard_cmd(one_time=False, inline=False)